### PR TITLE
Auth headers

### PR DESCRIPTION
**Pull request by carolynjonesconway**
### What’s this PR do?
Omits the "Authorization" header from requests where we don't have an auth key yet (i.e., when we're getting a client token for the first time).

Previously, if there was no client token available, we were sending this header: `Authorization ClientToken undefined`.

On the API side when we check for authorization headers, it's ok if the ClientToken is omitted, but we reject invalid client tokens. So `undefined` gets parsed as an invalid client token and the request is rejected :(

### Any background context you want to provide?
This came up because we added a decorator to one of our `api.before_request` functions. The decorator started checking this `undefined` client token and rejecting request before we have a chance to generate a valid one in the view.

The related API code is in [this PR](https://github.com/YesGraph/api.yesgraph.com/pull/784). See [this comment](https://github.com/YesGraph/api.yesgraph.com/pull/784/files#diff-a457ac0d1f149f9ee24cd2548cc9358aR39) in particular.

### Where should the reviewer start?
Review the changes to the `hitAPI` method in src/dev/modules/api.js
 
### Does this require changes on the API side?
We rolled-back the code causing the bug, but once this is merged we can deploy it again.

### How should this be manually tested?
To reproduce the error:
1. Run the API server & make sure you have the most recent changes from the master branch
2. Run `npm start` & go to [localhost:8080/demo_widget.html](http://localhost:8080/demo_widget.html) from an Incognito window
You should see console errors, like in the screenshot below.
3. Pull the changes from this branch & repeat.
The console errors should be gone and the widget should appear.

### What are the relevant tickets?
[Asana Task: Omit superwidget auth headers if auth key/token is missing](https://app.asana.com/0/59202558034519/231896473272741)
[Sentry Error: Invalid client token: undefined](https://sentry.io/yesgraph/superwidget/issues/152881897/)
[API PR #784](https://github.com/YesGraph/api.yesgraph.com/pull/784) (see [this comment](https://github.com/YesGraph/api.yesgraph.com/pull/784/files#diff-a457ac0d1f149f9ee24cd2548cc9358aR39))

### Screenshots (if appropriate)
screen shot 2016-12-15 at 12 34 09 pm

### Does the knowledge base need an update?
Nope

### CODE REVIEW

**Comment by carolynjonesconway** [comment]
I'll check out what's going on with travis :(

**Comment by mweiss17** [comment]
@carolynjonesconway the tests passed and the code looks good to me, so lemme know what's up with travis then we can merge it.

**Comment by mweiss17** [comment]
@carolynjonesconway actually thats a lie, two of the tests failed. Unsure why.

**Comment by mweiss17** [comment]
should we merge this? the tests passed for me locally and the unix tests passed for travis

**Comment by carolynjonesconway** [comment]
Yep, I'm ready!

**Pull request merged**
