### PR TITLE
Button bugfix

### PR DESCRIPTION
**Pull request by carolynjonesconway**
### What’s this PR do?
- Fixes a bug whereby clicking a contact row selects it properly, but clicking the checkbox itself has no effect.
- Fixes a bug whereby the Superwidget would render all the contact importing buttons even if some were supposed to be disabled.

A side-effect of this bug is that all five buttons would be shown, including text labels:
224917524433058 une6yrxnzbiulsc9eitc_height640

### Where should the reviewer start?
Start with src/dev/modules/view.js

### How should this be manually tested?
To test the contact importing buttons, try this before pulling the changes to reproduce the problem, and then after pulling them to see the solution:
1. On the Superwidget dashboard, enable all contact importing services for the demo app (with the `app_name` "YesGraph").
2. Run `npm start`, and look at your widget on [localhost:8080/demo_widget.html](http://localhost:8080/demo_widget.html). The buttons should look like this:
    screen shot 2016-12-09 at 11 50 45 am

3. Then disable all but one contact importing service. With the new changes, you should get a single button, like this:
    screen shot 2016-12-09 at 1 33 11 pm

I've also added an automated test for selecting contact rows, so running `npm test` will cover that bugfix.

I have a task to add tests for various configurations of superwidget options. That will make testing this more robust, but for now a manual test is the best we can do ¯\_(ツ)_/¯

### What are the relevant tickets?
[Asana Task: Debug Superwidget button size](https://app.asana.com/0/59202558034519/224917524433054)
[Asana Task: Fix broken checkboxes on the Superwidget modal](https://app.asana.com/0/59202558034519/228421746130731)

### CODE REVIEW

**Comment by carolynjonesconway** [comment]
The diff here is misleading. Many of the changes here were already reviewed and merged, so the new stuff is in src/dev/modules/view.js and in the tests.

This was a side-effect of the development cycle. Normally it works like this:
1. Make changes to the source code in src/dev/
2. Review & merge those changes
3. Deploy to the dev version of the cdn and doing any manual testing there
4. Updating the code at the _root_ of the src/ folder & deploying to the live CDN
5. Commit those updated files to the master branch

After we deployed the live version, I forgot to commit the updated files to the master branch, so it looks like they're included in this PR even though they were reviewed in the previous one.

**Comment by mweiss17** [comment]
search

Can we get a little pointer hand on the contact clicker?

**Comment by carolynjonesconway** [comment]
I set it to use the pointer; Note that demo_widget.html uses the CSS from the CDN, so to see the new styling you need demo_events.html

**Comment by mweiss17** [comment]
cool tests passed, gonna merge it

**Pull request merged**
